# Generated by Django 3.2.21 on 2023-10-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_auto_20230917_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
