# Generated by Django 3.2.21 on 2023-10-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_auto_20231001_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
    ]
